name: Node.js CI

on:
  push:
    branches: ["main"]

env:
  ASTRO_TELEMETRY_DISABLED: 1
  DO_NOT_TRACK: 1
  TURBO_TELEMETRY_DISABLED: 1

jobs:
  build_and_test_and_lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Cache turbo build setup
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          cache: "npm"
      - run: npm ci
      - run: npx turbo build test lint
